- name: Create 'app' group
  group:
    name: app
    state: present
    system: yes

- name: Create 'app' user
  user:
    name: app
    group: app
    state: present
    system: yes


- name: Create /certs
  file:
    path: /certs/
    state: directory
    mode: '0655'
    owner: app
    group: app

- name: Copy RDS root certificate
  copy:
    src: ../../certificates/
    dest: /certs/
    mode: 0644
    owner: app
    group: app

- name: Copy app service systemd config
  copy:
    src: ../../systemd/app.service
    dest: /etc/systemd/system/app.service
    mode: 0644

- name: Copy app target systemd config
  copy:
    src: ../../systemd/app.target
    dest: /etc/systemd/system/app.target
    mode: 0644

- name: Enable app service
  service:
    name: app
    enabled: yes

- name: Copy worker service systemd config
  copy:
    src: ../../systemd/worker.service
    dest: /etc/systemd/system/worker.service
    mode: 0644

- name: Copy worker target systemd config
  copy:
    src: ../../systemd/worker.target
    dest: /etc/systemd/system/worker.target
    mode: 0644

- name: Enable worker service
  service:
    name: worker
    enabled: yes
