- name: Disable nginx
  service:
    name: nginx
    enabled: no

- name: Copy service systemd config file
  copy:
    src: ../../systemd/nginx.service
    dest: /etc/systemd/system/nginx.service
    mode: 0644

- name: Copy nginx config file
  copy:
    src: ../../nginx/westrikworld_api.conf
    dest: /etc/nginx/sites-available/westrikworld_api.conf
    mode: 0644

- name: Symlink config to sites-enabled
  file:
    src: /etc/nginx/sites-available/westrikworld_api.conf
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Reload & enable nginx
  systemd:
    enabled: yes
    daemon_reload: yes
    name: nginx
