- name: Copy secrets script
  copy:
    src: ../../scripts/load_secrets.sh
    dest: /usr/bin/load_secrets
    mode: 0700

- name: Copy secrets service systemd config
  copy:
    src: ../../systemd/secrets.service
    dest: /etc/systemd/system/secrets.service
    mode: 0644

- name: Copy secrets target systemd config
  copy:
    src: ../../systemd/secrets.target
    dest: /etc/systemd/system/secrets.target
    mode: 0644

- name: Copy secrets timer systemd config
  copy:
    src: ../../systemd/secrets.timer
    dest: /etc/systemd/system/secrets.timer
    mode: 0644

- name: Enable secrets service
  service:
    name: secrets.service
    enabled: yes

- name: Enable secrets timer
  service:
    name: secrets.timer
    enabled: yes

- name: Enable secrets target
  service:
    name: secrets.target
    enabled: yes
