- name: Enable ufw logging
  ufw:
    logging: 'on'

- name: Deny all incoming and outgoing connections
  ufw:
    policy: deny

- name: Allow outbound DNS
  ufw:
    rule: allow
    port: '53'
    direction: out

- name: Allow inbound ssh
  ufw:
    rule: allow
    port: '22'
    direction: in
# todo: limit to only VPC

- name: Limit brute-force ssh connections
  ufw:
    rule: limit
    port: '22'
    proto: tcp

- name: Allow http
  ufw:
    rule: allow
    port: '80'

- name: Allow https
  ufw:
    rule: allow
    port: '443'

- name: Allow postgres port
  ufw:
    rule: allow
    port: '5543'
    direction: out

- name: Allow Consul DNS
  ufw:
    rule: allow
    port: '8600'

- name: Allow Consul HTTP
  ufw:
    rule: allow
    port: '8500'

- name: Allow Consul HTTPS
  ufw:
    rule: allow
    port: '8501'

- name: Allow Consul gRPC
  ufw:
    rule: allow
    port: '8502'

- name: Allow Consul Server RPC
  ufw:
    rule: allow
    port: '8300'

- name: Allow Consul Serf LAN
  ufw:
    rule: allow
    port: '8301'

- name: Allow Consul Serf WAN
  ufw:
    rule: allow
    port: '8302'

- name: Allow Nomad HTTP
  ufw:
    rule: allow
    port: '4646'

- name: Allow Nomad RPC
  ufw:
    rule: allow
    port: '4647'

- name: Allow Nomad Serf WAN
  ufw:
    rule: allow
    port: '4648'

- name: Start ufw now and at boot
  ufw:
    state: enabled
