repos:
# - repo: local
#   hooks:
#   - id: cargo-check
#     name: Check Rust files
#     entry: cd server && cargo check
#     language: script
#   - id: cargo-clippy
#     name: Run clippy on Rust files
#     entry: cd server && cargo clippy
#     language: script
#   - id: cargo-fmt
#     name: Format Rust files
#     entry: cd server && cargo fmt
#     language: script
#   - id: yarn-check
#     name: Check web client
#     entry: cd client-web && yarn run chk
#     language: script
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.28.0
  hooks:
  - id: terraform_fmt
    files: infra
  - id: terraform_validate
    files: infra
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
