source 'https://github.com/CocoaPods/Specs.git'

target "westrikworld" do
  platform :osx, "10.14"
  inhibit_all_warnings!
  pod 'AppCenter'
  pod 'SwiftyJSON'
  pod 'Sparkle'
  pod 'Alamofire'
end

target "westrikworld-MAS" do
  platform :osx, "10.14"
  inhibit_all_warnings!
  pod 'AppCenter'
  pod 'SwiftyJSON'
  pod 'Alamofire'
end
