[package]
name = "timeline-server"
version = "0.1.0"
authors = ["Matt Westrik <m@ttwestrik.com>"]
edition = "2018"

[dependencies]
actix-files = "^0.1"
actix-session = "^0.2.0"
actix-web = "^1.0.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { features = ["postgres", "r2d2", "chrono"], version = "1.3.2" }
dotenv = "^0.14"
env_logger = "^0.7"
futures = "^0.1"
log = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
