- name: Download CodeDeploy Agent
  get_url:
    url: "https://aws-codedeploy-{{ aws_region }}.s3.amazonaws.com/latest/install"
    dest: /tmp/codedeploy-install
    mode: 0755

- name: Install CodeDeploy
  shell: AWS_REGION={{ aws_region }} /tmp/codedeploy-install auto
