---
- name: Add HashiCorp apt GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com buster main
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Choose apt policy for consul
  shell: apt-cache policy consul

- name: Install consul
  apt:
    name: consul
    state: present

- name: Install nomad
  apt:
    name: nomad
    state: present
