- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Install ruby
  apt:
    name: ruby
    state: present

- name: Install awscli
  apt:
    name: awscli
    state: present
