#!/usr/bin/env bash

BRANCH=$1
if [ -z "$BRANCH" ]; then
  BRANCH="master"
fi

set -euo pipefail

PROJECT_PATH="/home/matt/src/world"
# TODO: check for dependencies
   
cd "$PROJECT_PATH";
cd server;
git stash;
git fetch origin $BRANCH;
git checkout "origin/$BRANCH";
cd -;
NODE_ENV=staging make;
sudo systemctl stop westrikworld_server
sudo cp "$PROJECT_PATH/server/target/release/run_server" /usr/bin/run_server
sudo chmod +x /usr/bin/run_server
sudo systemctl start westrikworld_server
sudo rm -rf /var/www/westrikworld;
sudo cp -r "$PROJECT_PATH/client-web/dist" /var/www/westrikworld
echo "deployed!"
