---
- name: Configure Debian AMI for westrikworld production
  hosts: all
  become: true
  vars:
    aws_region: "us-east-1"

  module_defaults:
    apt:
      force_apt_get: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Consul & Nomad
      import_tasks: dependencies/hashicorp.yml

    - name: Install service dependencies
      import_tasks: dependencies/service.yml

    - name: Set up firewall
      import_tasks: config/ufw.yml

    # TODO: replace this functionality with Nomad/Vault
    - name: Configure secrets service
      import_tasks: config/secrets.yml

    - name: Configure app services
      import_tasks: config/app.yml

    - name: Configure nginx
      import_tasks: config/nginx.yml

    - name: Configure Consul
      import_tasks: config/consul.yml

    - name: Configure Nomad
      import_tasks: config/nomad.yml
