version: 0.0
os: linux
files:
  - source: bin/api_server
    destination: /usr/bin/api_server
  - source: bin/worker
    destination: /usr/bin/worker
hooks:
  ApplicationStop:
    - location: bin/deploy_stop.sh
      timeout: 300
  ApplicationStart:
    - location: bin/deploy_start.sh
      timeout: 30
  ValidateService:
    - location: bin/validate_service.sh
      timeout: 30
