name: Release (Docker)
on: push
#   push:
#     tags:
#       - v*
#   release:
#     types: [created, edited, published]

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build & push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mattwestrik/ww
          tags: latest
