name: Release (Docker)
on:
   push:
     branches:
       - dev

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build & push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mattwestrik/ww
          tags: latest
