name: release
on: push
#  release:
#    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install libpq-dev
        run: sudo apt-get install libpq-dev
      - name: Build
        working-directory: ./server
        run: cargo build --verbose --release
      - name: set up node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: yarn install & build
        working-directory: ./web-client
        run: |
          yarn install
          yarn build
      - name: bundle
        run: bash ./infra/codedeploy/bin/zip_app_bundle.sh
      - name: Upload bundle to S3 bucket
        uses: westrik/s3-cp-action@master
        with:
          args: --acl private
        env:
          FILE: ./westrikworld_app.zip
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
