name: Profile Build
on: push
# TODO: on push to main branch

jobs:
  timings:
    name: Profile cargo build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install libpq-dev
        run: bash scripts/setup_test_env.sh
      - name: Build with -Z timings
        run: cargo build --verbose --features "production" -Z timings
#      - name: Upload bundle to S3 bucket
#        uses: westrik/s3-cp-action@master
#        with:
#          args: --acl private
#        env:
#          FILE: ./westrikworld_app.zip
#          AWS_REGION: 'us-east-1'
#          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
