name: Web

on: [push]

jobs:
  build-and-test:
    name: build & test web client
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install, build, and test
      working-directory: ./web-client
      run: |
        yarn install
        yarn build
        yarn test
      env:
        CI: true
    - name: Lint and type-check
      working-directory: ./web-client
      run: |
        yarn lint
        yarn tsc
