name: Web

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: yarn install; build & test
      working-directory: ./web-client
      run: |
        yarn install
        yarn build
        yarn test
      env:
        CI: true
    - name: lint & type-check
      working-directory: ./web-client
      run: |
        yarn lint
        yarn tsc
